[0m2024-04-27 00:01:14 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 00:01:15 V/: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 00:01:28 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 00:01:29 V/: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 00:02:26 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 00:02:26 V/: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 00:02:49 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 00:02:49 V/: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 00:04:24 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 00:04:25 V/: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 00:06:18 V/: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2024-04-27 00:06:18 V/: Recv: friendlist.GetTroopListReqV2[0m
[0m2024-04-27 00:06:18 V/: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2024-04-27 00:06:19 V/: Recv: friendlist.GetTroopMemberListReq[0m
[0m2024-04-27 00:06:19 V/: Send: ProfileService.Pb.ReqSystemMsgNew.Group(ProfileService.Pb.ReqSystemMsgNew.Group)[0m
[96m2024-04-27 00:06:19 D/: Unknown Transformers528 0x14 template
templId=10063
PermList=[TemplParam#681881273 {
            name=invite_qq_nick
            value=1178669866
    }][0m
[96m2024-04-27 00:06:19 D/: Unknown Transformers528 0x14 template
templId=10179
PermList=[TemplParam#681881273 {
            name=invitor
            value=1178669866
    }, TemplParam#681881273 {
            name=invitee
            value=3783234325
    }][0m
[0m2024-04-27 00:06:19 V/: Recv: ProfileService.Pb.ReqSystemMsgNew.Group[0m
[0m2024-04-27 00:06:53 V/: Send: MultiMsg.ApplyUp(MultiMsg.ApplyUp)[0m
[0m2024-04-27 00:06:54 V/: Recv: MultiMsg.ApplyUp[0m
[0m2024-04-27 00:06:54 V/: [Highway] Uploading forward message to 14.116.241.44:80, size=1.21 KiB[0m
[0m2024-04-27 00:06:54 V/: [Highway] Uploading forward message: succeed at 15 KiB/s[0m
[0m2024-04-27 00:06:54 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 00:06:54 V/: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 07:30:37 V/Net 3783234325: Validated caches.[0m
[0m2024-04-27 07:30:37 V/Net 3783234325: Loading server list from cache.[0m
[0m2024-04-27 07:30:37 V/Net 3783234325: Server list: 117.62.240.80:8080, 114.221.144.150:80, 117.62.243.221:14000, 49.7.253.45:443, 49.7.253.177:443, 42.81.184.82:80, 183.47.107.174:8080, msfwifi.3g.qq.com:8080, 42.81.184.82:8080, 183.47.102.193:14000.[0m
[92m2024-04-27 07:30:38 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:30:38 V/Net 3783234325: Send: wtlogin.exchange_emp(10:fast-login)[0m
[0m2024-04-27 07:30:39 V/Net 3783234325: Recv: wtlogin.exchange_emp[0m
[93m2024-04-27 07:30:39 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-04-27 07:30:39 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:30:39 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 07:30:39 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Password@625465884[0m
[0m2024-04-27 07:30:39 V/Net 3783234325: Send: wtlogin.login(9:password-login)[0m
[0m2024-04-27 07:30:39 V/Net 3783234325: Recv: wtlogin.login[0m
[93m2024-04-27 07:30:39 W/Net 3783234325: Failed with auth method: Password@625465884
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-04-27 07:30:39 V/Net 3783234325: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)[0m
[92m2024-04-27 07:30:42 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:30:42 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 07:30:42 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@1123876167[0m
[93m2024-04-27 07:30:42 W/Net 3783234325: Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@1123876167
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	... 5 more
[0m
[93m2024-04-27 07:30:42 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
	Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(3783234325), code=40, title=安全提醒, message=请确认你输入了正确的账号。该账号存在被盗风险，已进入保护模式，请前往安全中心恢复。, errorInfo= )
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:528)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]
[0m
[93m2024-04-27 07:30:42 W/Net 3783234325: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-04-27 07:31:35 V/Net 3783234325: Validated caches.[0m
[0m2024-04-27 07:31:35 V/Net 3783234325: Loading server list from cache.[0m
[0m2024-04-27 07:31:35 V/Net 3783234325: Server list: 117.62.240.80:8080, 114.221.144.150:80, 117.62.243.221:14000, 49.7.253.45:443, 49.7.253.177:443, 42.81.184.82:80, 183.47.107.174:8080, msfwifi.3g.qq.com:8080, 42.81.184.82:8080, 183.47.102.193:14000.[0m
[92m2024-04-27 07:31:36 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:31:36 V/Net 3783234325: Send: wtlogin.exchange_emp(10:fast-login)[0m
[0m2024-04-27 07:31:37 V/Net 3783234325: Recv: wtlogin.exchange_emp[0m
[93m2024-04-27 07:31:37 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-04-27 07:31:37 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:31:37 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 07:31:37 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Password@27017646[0m
[0m2024-04-27 07:31:37 V/Net 3783234325: Send: wtlogin.login(9:password-login)[0m
[0m2024-04-27 07:31:37 V/Net 3783234325: Recv: wtlogin.login[0m
[93m2024-04-27 07:31:37 W/Net 3783234325: Failed with auth method: Password@27017646
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-04-27 07:31:37 V/Net 3783234325: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)[0m
[92m2024-04-27 07:31:40 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:31:40 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 07:31:40 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@1294080335[0m
[93m2024-04-27 07:31:40 W/Net 3783234325: Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@1294080335
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	... 5 more
[0m
[93m2024-04-27 07:31:40 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
	Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(3783234325), code=40, title=安全提醒, message=请确认你输入了正确的账号。该账号存在被盗风险，已进入保护模式，请前往安全中心恢复。, errorInfo= )
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:528)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]
[0m
[93m2024-04-27 07:31:40 W/Net 3783234325: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-04-27 07:33:12 V/Net 3783234325: Validated caches.[0m
[0m2024-04-27 07:33:12 V/Net 3783234325: Loading server list from cache.[0m
[0m2024-04-27 07:33:12 V/Net 3783234325: Server list: 117.62.240.80:8080, 114.221.144.150:80, 117.62.243.221:14000, 49.7.253.45:443, 49.7.253.177:443, 42.81.184.82:80, 183.47.107.174:8080, msfwifi.3g.qq.com:8080, 42.81.184.82:8080, 183.47.102.193:14000.[0m
[92m2024-04-27 07:33:13 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:33:13 V/Net 3783234325: Send: wtlogin.exchange_emp(10:fast-login)[0m
[0m2024-04-27 07:33:13 V/Net 3783234325: Recv: wtlogin.exchange_emp[0m
[93m2024-04-27 07:33:13 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-04-27 07:33:13 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:33:13 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 07:33:13 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Password@1096961778[0m
[0m2024-04-27 07:33:14 V/Net 3783234325: Send: wtlogin.login(9:password-login)[0m
[0m2024-04-27 07:33:14 V/Net 3783234325: Recv: wtlogin.login[0m
[93m2024-04-27 07:33:14 W/Net 3783234325: Failed with auth method: Password@1096961778
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-04-27 07:33:14 V/Net 3783234325: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)[0m
[92m2024-04-27 07:33:17 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:33:17 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 07:33:17 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@928623393[0m
[93m2024-04-27 07:33:17 W/Net 3783234325: Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@928623393
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	... 5 more
[0m
[93m2024-04-27 07:33:17 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
	Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:528)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]
[0m
[93m2024-04-27 07:33:17 W/Net 3783234325: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-04-27 07:33:47 V/Net 3783234325: Validated caches.[0m
[0m2024-04-27 07:33:47 V/Net 3783234325: Loading server list from cache.[0m
[0m2024-04-27 07:33:47 V/Net 3783234325: Server list: 117.62.240.80:8080, 114.221.144.150:80, 117.62.243.221:14000, 49.7.253.45:443, 49.7.253.177:443, 42.81.184.82:80, 183.47.107.174:8080, msfwifi.3g.qq.com:8080, 42.81.184.82:8080, 183.47.102.193:14000.[0m
[92m2024-04-27 07:33:48 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:33:48 V/Net 3783234325: Send: wtlogin.exchange_emp(10:fast-login)[0m
[0m2024-04-27 07:33:48 V/Net 3783234325: Recv: wtlogin.exchange_emp[0m
[93m2024-04-27 07:33:48 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-04-27 07:33:48 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:33:48 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 07:33:48 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Password@2082798933[0m
[0m2024-04-27 07:33:48 V/Net 3783234325: Send: wtlogin.login(9:password-login)[0m
[0m2024-04-27 07:33:48 V/Net 3783234325: Recv: wtlogin.login[0m
[93m2024-04-27 07:33:48 W/Net 3783234325: Failed with auth method: Password@2082798933
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-04-27 07:33:48 V/Net 3783234325: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)[0m
[92m2024-04-27 07:33:51 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:33:51 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 07:33:51 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@1056567570[0m
[93m2024-04-27 07:33:51 W/Net 3783234325: Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@1056567570
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	... 5 more
[0m
[93m2024-04-27 07:33:51 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
	Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:528)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]
[0m
[93m2024-04-27 07:33:51 W/Net 3783234325: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-04-27 07:34:14 V/Net 3783234325: Validated caches.[0m
[0m2024-04-27 07:34:14 V/Net 3783234325: Loading server list from cache.[0m
[0m2024-04-27 07:34:14 V/Net 3783234325: Server list: 117.62.240.80:8080, 114.221.144.150:80, 117.62.243.221:14000, 49.7.253.45:443, 49.7.253.177:443, 42.81.184.82:80, 183.47.107.174:8080, msfwifi.3g.qq.com:8080, 42.81.184.82:8080, 183.47.102.193:14000.[0m
[92m2024-04-27 07:34:15 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:34:15 V/Net 3783234325: Send: wtlogin.exchange_emp(10:fast-login)[0m
[0m2024-04-27 07:34:15 V/Net 3783234325: Recv: wtlogin.exchange_emp[0m
[93m2024-04-27 07:34:15 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-04-27 07:34:15 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:34:15 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 07:34:15 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Password@2036893943[0m
[0m2024-04-27 07:34:15 V/Net 3783234325: Send: wtlogin.login(9:password-login)[0m
[0m2024-04-27 07:34:16 V/Net 3783234325: Recv: wtlogin.login[0m
[93m2024-04-27 07:34:16 W/Net 3783234325: Failed with auth method: Password@2036893943
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-04-27 07:34:16 V/Net 3783234325: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)[0m
[92m2024-04-27 07:34:19 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:34:19 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 07:34:19 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@1953810666[0m
[93m2024-04-27 07:34:19 W/Net 3783234325: Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@1953810666
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	... 5 more
[0m
[93m2024-04-27 07:34:19 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
	Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:528)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]
[0m
[93m2024-04-27 07:34:19 W/Net 3783234325: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-04-27 07:35:30 V/Net 3783234325: Validated caches.[0m
[0m2024-04-27 07:35:30 V/Net 3783234325: Loading server list from cache.[0m
[0m2024-04-27 07:35:30 V/Net 3783234325: Server list: 117.62.240.80:8080, 114.221.144.150:80, 117.62.243.221:14000, 49.7.253.45:443, 49.7.253.177:443, 42.81.184.82:80, 183.47.107.174:8080, msfwifi.3g.qq.com:8080, 42.81.184.82:8080, 183.47.102.193:14000.[0m
[92m2024-04-27 07:35:31 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:35:31 V/Net 3783234325: Send: wtlogin.exchange_emp(10:fast-login)[0m
[0m2024-04-27 07:35:31 V/Net 3783234325: Recv: wtlogin.exchange_emp[0m
[93m2024-04-27 07:35:31 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-04-27 07:35:31 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:35:31 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 07:35:31 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Password@281733484[0m
[0m2024-04-27 07:35:31 V/Net 3783234325: Send: wtlogin.login(9:password-login)[0m
[0m2024-04-27 07:35:32 V/Net 3783234325: Recv: wtlogin.login[0m
[93m2024-04-27 07:35:32 W/Net 3783234325: Failed with auth method: Password@281733484
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-04-27 07:35:32 V/Net 3783234325: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)[0m
[92m2024-04-27 07:35:35 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 07:35:35 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 07:35:35 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@983505400[0m
[93m2024-04-27 07:35:35 W/Net 3783234325: Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@983505400
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	... 5 more
[0m
[93m2024-04-27 07:35:35 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
	Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:528)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]
[0m
[93m2024-04-27 07:35:35 W/Net 3783234325: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-04-27 23:01:02 V/Net 3783234325: Validated caches.[0m
[0m2024-04-27 23:01:02 V/Net 3783234325: Loading server list from cache.[0m
[0m2024-04-27 23:01:02 V/Net 3783234325: Server list: 117.62.240.80:8080, 114.221.144.150:80, 117.62.243.221:14000, 49.7.253.45:443, 49.7.253.177:443, 42.81.184.82:80, 183.47.107.174:8080, msfwifi.3g.qq.com:8080, 42.81.184.82:8080, 183.47.102.193:14000.[0m
[92m2024-04-27 23:01:03 I/Net 3783234325: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-04-27 23:01:03 I/Net 3783234325: Successfully fetched ecdh public key from server.[0m
[0m2024-04-27 23:01:03 V/Net 3783234325: Send: wtlogin.exchange_emp(10:fast-login)[0m
[0m2024-04-27 23:01:04 V/Net 3783234325: Recv: wtlogin.exchange_emp[0m
[93m2024-04-27 23:01:04 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-04-27 23:01:04 I/Net 3783234325: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-04-27 23:01:04 I/Net 3783234325: Successfully fetched ecdh public key from server.[0m
[0m2024-04-27 23:01:04 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 23:01:04 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Password@143191080[0m
[0m2024-04-27 23:01:04 V/Net 3783234325: Send: wtlogin.login(9:password-login)[0m
[0m2024-04-27 23:01:04 V/Net 3783234325: Recv: wtlogin.login[0m
[93m2024-04-27 23:01:04 W/Net 3783234325: Failed with auth method: Password@143191080
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-04-27 23:01:04 V/Net 3783234325: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)[0m
[92m2024-04-27 23:01:07 I/Net 3783234325: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-04-27 23:01:07 I/Net 3783234325: Successfully fetched ecdh public key from server.[0m
[0m2024-04-27 23:01:07 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 23:01:07 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@1499322933[0m
[93m2024-04-27 23:01:07 W/Net 3783234325: Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]@1499322933
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	... 6 more
[0m
[93m2024-04-27 23:01:07 W/Net 3783234325: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
	... 34 more
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		... 6 more
	Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:528)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		... 6 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3783234325), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)]
[0m
[93m2024-04-27 23:01:07 W/Net 3783234325: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-04-27 23:03:54 V/Net 3783234325: Hash not match. Invaliding caches.....[0m
[0m2024-04-27 23:03:54 V/Net 3783234325: No server list cached.[0m
[92m2024-04-27 23:03:55 I/Net 3783234325: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-04-27 23:03:55 I/Net 3783234325: Successfully fetched ecdh public key from server.[0m
[0m2024-04-27 23:03:55 V/Net 3783234325: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-04-27 23:03:55 D/Net 3783234325: [AuthControl/acquire] Authorization responded: Password@770852753[0m
[0m2024-04-27 23:03:56 V/Net 3783234325: Send: wtlogin.login(9:password-login)[0m
[0m2024-04-27 23:03:56 V/Net 3783234325: Recv: wtlogin.login[0m
[0m2024-04-27 23:04:34 V/Net 3783234325: Send: wtlogin.login(2:submit-slider)[0m
[0m2024-04-27 23:04:35 V/Net 3783234325: Recv: wtlogin.login[0m
[0m2024-04-27 23:04:40 V/Net 3783234325: Send: wtlogin.login(8:request-sms)[0m
[0m2024-04-27 23:04:40 V/Net 3783234325: Recv: wtlogin.login[0m
[0m2024-04-27 23:04:50 V/Net 3783234325: Send: wtlogin.login(7:submit-sms)[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Recv: wtlogin.login[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: [AuthControl/resume] Fire auth completed[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Send: StatSvc.register(online)[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Server time updated, serverTime: 1714230289, diff: -2ms=-0.002s[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Recv: StatSvc.register[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: No BdhSession cache[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Syncing friend message history...[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Start loading stranger list...[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Start loading friend list...[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Start loading friendGroup list...[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Recv: StatSvc.GetDevLoginInfo[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: No OtherClient online.[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Recv: OidbSvc.0x5d2_0[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Successfully loaded stranger list: 0 in total[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Recv: OidbSvc.0x496[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Start loading group list...[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Recv: friendlist.getFriendGroupList[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Loading friend list: 5/5[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Successfully loaded friend list: 5 in total[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Recv: friendlist.getFriendGroupList[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Loading friendGroup list: 1/1[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Successfully loaded friendGroup list: 1 in total[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Recv: friendlist.GetTroopListReqV2[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Recv: friendlist.GetTroopMemberListReq[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Recv: friendlist.GetTroopMemberListReq[0m
[0m2024-04-27 23:04:51 V/Net 3783234325: Recv: friendlist.GetTroopMemberListReq[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Successfully loaded group list: 3 in total.[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Scheduled key refresh in 23h 55min 0.0s.[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[92m2024-04-27 23:04:51 I/Net 3783234325: Syncing friend message history: Success.[0m
[0m2024-04-27 23:04:54 V/Net 3783234325: Server list: 49.7.253.65:8080, 114.221.144.150:14000, 183.47.99.24:8080, 121.229.94.199:8080, 222.94.109.78:80, 119.147.190.138:14000, msfwifi.3g.qq.com:8080, 49.7.253.45:443, 49.7.253.214:80, 49.7.253.177:443.[0m
[0m2024-04-27 23:04:54 V/Net 3783234325: No BdhSession to save to cache[0m
[0m2024-04-27 23:04:54 V/Net 3783234325: Saving server list to cache[0m
[0m2024-04-27 23:04:54 V/Net 3783234325: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2024-04-27 23:04:54 V/Net 3783234325: Recv: ConfigPushSvc.PushReq[0m
[0m2024-04-27 23:04:54 V/Net 3783234325: Saving bdh session to cache[0m
[0m2024-04-27 23:04:54 V/Net 3783234325: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2024-04-27 23:04:54 V/Net 3783234325: Recv: ConfigPushSvc.PushReq[0m
[0m2024-04-27 23:05:48 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:05:48 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:07:45 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:07:45 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:08:42 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:08:42 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:11:12 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:11:12 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:12:21 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:12:21 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:12:56 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:12:57 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:13:18 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:13:19 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:13:38 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:13:39 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:13:42 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:13:42 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:14:01 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:14:02 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:14:19 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:14:19 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:14:30 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:14:30 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:14:40 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:14:40 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:15:52 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:15:53 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:16:05 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:16:05 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:16:37 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:16:37 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:16:46 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:16:46 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:17:04 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:17:04 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:17:23 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:17:23 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:17:25 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:17:25 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:18:23 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:18:24 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:20:32 V/Net 3783234325: Send: ProfileService.Pb.ReqSystemMsgNew.Friend(ProfileService.Pb.ReqSystemMsgNew.Friend)[0m
[0m2024-04-27 23:20:33 V/Net 3783234325: Recv: ProfileService.Pb.ReqSystemMsgNew.Friend[0m
[0m2024-04-27 23:21:13 V/Net 3783234325: Send: ProfileService.Pb.ReqSystemMsgNew.Group(ProfileService.Pb.ReqSystemMsgNew.Group)[0m
[0m2024-04-27 23:21:13 V/Net 3783234325: Recv: ProfileService.Pb.ReqSystemMsgNew.Group[0m
[0m2024-04-27 23:21:14 V/Net 3783234325: Send: ProfileService.Pb.ReqSystemMsgNew.Group(ProfileService.Pb.ReqSystemMsgNew.Group)[0m
[0m2024-04-27 23:21:14 V/Net 3783234325: Recv: ProfileService.Pb.ReqSystemMsgNew.Group[0m
[0m2024-04-27 23:21:40 V/Net 3783234325: Send: StatSvc.register(offline)[0m
[0m2024-04-27 23:22:43 V/Net 3783234325: Validated caches.[0m
[0m2024-04-27 23:22:43 V/Net 3783234325: Loading server list from cache.[0m
[0m2024-04-27 23:22:43 V/Net 3783234325: Server list: 49.7.253.65:8080, 114.221.144.150:14000, 183.47.99.24:8080, 121.229.94.199:8080, 222.94.109.78:80, 119.147.190.138:14000, msfwifi.3g.qq.com:8080, 49.7.253.45:443, 49.7.253.214:80, 49.7.253.177:443.[0m
[92m2024-04-27 23:22:44 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 23:22:45 V/Net 3783234325: Send: wtlogin.exchange_emp(10:fast-login)[0m
[0m2024-04-27 23:22:45 V/Net 3783234325: Recv: wtlogin.exchange_emp[0m
[0m2024-04-27 23:22:45 V/Net 3783234325: Send: StatSvc.register(online)[0m
[92m2024-04-27 23:22:45 I/Net 3783234325: Server time updated, serverTime: 1714231362, diff: -3ms=-0.003s[0m
[0m2024-04-27 23:22:45 V/Net 3783234325: Recv: StatSvc.register[0m
[0m2024-04-27 23:22:45 V/Net 3783234325: Loading BdhSession from cache file[0m
[92m2024-04-27 23:22:45 I/Net 3783234325: Syncing friend message history...[0m
[92m2024-04-27 23:22:45 I/Net 3783234325: Start loading friend list...[0m
[92m2024-04-27 23:22:45 I/Net 3783234325: Start loading stranger list...[0m
[92m2024-04-27 23:22:45 I/Net 3783234325: Start loading friendGroup list...[0m
[0m2024-04-27 23:22:45 V/Net 3783234325: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[0m2024-04-27 23:22:45 V/Net 3783234325: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2024-04-27 23:22:45 V/Net 3783234325: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2024-04-27 23:22:45 V/Net 3783234325: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2024-04-27 23:22:45 V/Net 3783234325: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2024-04-27 23:22:45 V/Net 3783234325: Send: StatSvc.RspMSFForceOffline(StatSvc.RspMSFForceOffline)[0m
[0m2024-04-27 23:22:45 V/Net 3783234325: Recv: StatSvc.ReqMSFOffline[0m
[93m2024-04-27 23:22:45 W/Net 3783234325: An exception was thrown during 'loading friends' of Bot 3783234325. Trying to ignore the error and continue logging in...
StateSwitchingException(old=StateLoading, new=StateClosed, cause=MsfOfflineToken(uin=3783234325, seq=3030302648, const=0))
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:352)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler.close(CommonNetworkHandler.kt:425)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:108)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:326)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:281)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:108)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:106)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:161)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:103)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: MsfOfflineToken(uin=3783234325, seq=3030302648, const=0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:299)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:586)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:158)
	... 22 more
[0m
[91m2024-04-27 23:22:45 E/Net 3783234325: Exception in coroutine 'unnamed'
MsfOfflineToken(uin=3783234325, seq=3030302648, const=0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:299)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:586)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:158)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:103)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
[0m
[93m2024-04-27 23:22:45 W/Net 3783234325: An exception was thrown during 'loading otherClients' of Bot 3783234325. Trying to ignore the error and continue logging in...
StateSwitchingException(old=StateLoading, new=StateClosed, cause=MsfOfflineToken(uin=3783234325, seq=3030302648, const=0))
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:352)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler.close(CommonNetworkHandler.kt:425)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:108)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:326)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:281)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:108)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:106)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:161)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:103)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: MsfOfflineToken(uin=3783234325, seq=3030302648, const=0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:299)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:586)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:158)
	... 22 more
[0m
[93m2024-04-27 23:22:45 W/Net 3783234325: An exception was thrown during 'loading groups' of Bot 3783234325. Trying to ignore the error and continue logging in...
StateSwitchingException(old=StateLoading, new=StateClosed, cause=MsfOfflineToken(uin=3783234325, seq=3030302648, const=0))
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:352)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler.close(CommonNetworkHandler.kt:425)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:108)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:326)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:281)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:108)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:106)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:161)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:103)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: MsfOfflineToken(uin=3783234325, seq=3030302648, const=0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:299)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:586)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:158)
	... 22 more
[0m
[93m2024-04-27 23:22:45 W/Net 3783234325: An exception was thrown during 'loading OtherClients' of Bot 3783234325. Trying to ignore the error and continue logging in...
StateSwitchingException(old=StateLoading, new=StateClosed, cause=MsfOfflineToken(uin=3783234325, seq=3030302648, const=0))
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:352)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler.close(CommonNetworkHandler.kt:425)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:108)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:326)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:281)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:108)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:106)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:161)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:103)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: MsfOfflineToken(uin=3783234325, seq=3030302648, const=0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:299)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:586)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:158)
	... 22 more
[0m
[93m2024-04-27 23:22:45 W/Net 3783234325: An exception was thrown during 'loading friendGroups' of Bot 3783234325. Trying to ignore the error and continue logging in...
StateSwitchingException(old=StateLoading, new=StateClosed, cause=MsfOfflineToken(uin=3783234325, seq=3030302648, const=0))
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:352)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler.close(CommonNetworkHandler.kt:425)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:108)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:326)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:281)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:108)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:106)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:161)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:103)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: MsfOfflineToken(uin=3783234325, seq=3030302648, const=0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:299)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:586)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:158)
	... 22 more
[0m
[91m2024-04-27 23:22:45 E/Net 3783234325: Exception in coroutine 'BotInitProcessor.init'
java.lang.IllegalStateException: Exception in attached Job 'BotInitProcessor.init'
	at net.mamoe.mirai.internal.network.handler.state.JobAttachStateObserver$stateChanged0$1.invokeSuspend(JobAttachStateObserver.kt:40)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: MsfOfflineToken(uin=3783234325, seq=3030302648, const=0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:299)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:586)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:158)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:103)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: StateSwitchingException(old=StateLoading, new=StateClosed, cause=MsfOfflineToken(uin=3783234325, seq=3030302648, const=0))
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:352)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler.close(CommonNetworkHandler.kt:425)
		at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:108)
		at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:326)
		at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:281)
		at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
		at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:108)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
		at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
		at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
		at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
		at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:106)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:161)
		... 22 more
	Caused by: [CIRCULAR REFERENCE: MsfOfflineToken(uin=3783234325, seq=3030302648, const=0)]
[0m
[0m2024-04-27 23:24:52 V/Net 3783234325: Validated caches.[0m
[0m2024-04-27 23:24:52 V/Net 3783234325: Loading server list from cache.[0m
[0m2024-04-27 23:24:52 V/Net 3783234325: Server list: 49.7.253.65:8080, 114.221.144.150:14000, 183.47.99.24:8080, 121.229.94.199:8080, 222.94.109.78:80, 119.147.190.138:14000, msfwifi.3g.qq.com:8080, 49.7.253.45:443, 49.7.253.214:80, 49.7.253.177:443.[0m
[92m2024-04-27 23:24:54 I/Net 3783234325: ECDH key is valid.[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Send: wtlogin.exchange_emp(10:fast-login)[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Recv: wtlogin.exchange_emp[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Send: StatSvc.register(online)[0m
[92m2024-04-27 23:24:54 I/Net 3783234325: Server time updated, serverTime: 1714231493, diff: -1ms=-0.001s[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Recv: StatSvc.register[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Loading BdhSession from cache file[0m
[92m2024-04-27 23:24:54 I/Net 3783234325: Syncing friend message history...[0m
[92m2024-04-27 23:24:54 I/Net 3783234325: Start loading friend list...[0m
[92m2024-04-27 23:24:54 I/Net 3783234325: Start loading stranger list...[0m
[92m2024-04-27 23:24:54 I/Net 3783234325: Start loading friendGroup list...[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Recv: StatSvc.GetDevLoginInfo[0m
[92m2024-04-27 23:24:54 I/Net 3783234325: No OtherClient online.[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Recv: OidbSvc.0x5d2_0[0m
[92m2024-04-27 23:24:54 I/Net 3783234325: Successfully loaded stranger list: 0 in total[0m
[92m2024-04-27 23:24:54 I/Net 3783234325: Start loading group list...[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Recv: OidbSvc.0x496[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Recv: friendlist.getFriendGroupList[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Loading friendGroup list: 1/1[0m
[92m2024-04-27 23:24:54 I/Net 3783234325: Successfully loaded friendGroup list: 1 in total[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Recv: friendlist.getFriendGroupList[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Loading friend list: 6/6[0m
[92m2024-04-27 23:24:54 I/Net 3783234325: Successfully loaded friend list: 6 in total[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Recv: friendlist.GetTroopListReqV2[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2024-04-27 23:24:54 V/Net 3783234325: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[92m2024-04-27 23:24:54 I/Net 3783234325: Syncing friend message history: Success.[0m
[0m2024-04-27 23:24:55 V/Net 3783234325: Recv: friendlist.GetTroopMemberListReq[0m
[0m2024-04-27 23:24:55 V/Net 3783234325: Recv: friendlist.GetTroopMemberListReq[0m
[0m2024-04-27 23:24:55 V/Net 3783234325: Recv: friendlist.GetTroopMemberListReq[0m
[0m2024-04-27 23:24:55 V/Net 3783234325: Recv: friendlist.GetTroopMemberListReq[0m
[92m2024-04-27 23:24:55 I/Net 3783234325: Successfully loaded group list: 4 in total.[0m
[92m2024-04-27 23:24:55 I/Net 3783234325: Scheduled key refresh in 23h 55min 0.0s.[0m
[92m2024-04-27 23:24:55 I/Net 3783234325: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[0m2024-04-27 23:24:57 V/Net 3783234325: Server list: 180.109.192.57:8080, 49.7.253.65:8080, 183.47.103.84:8080, 49.7.253.65:80, 183.47.126.26:14000, 114.221.144.150:14000, 42.81.193.250:443, 117.62.243.221:80, 49.7.253.177:443, msfwifi.3g.qq.com:8080.[0m
[0m2024-04-27 23:24:57 V/Net 3783234325: Saving bdh session to cache[0m
[0m2024-04-27 23:24:57 V/Net 3783234325: Saving server list to cache[0m
[0m2024-04-27 23:24:57 V/Net 3783234325: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2024-04-27 23:24:57 V/Net 3783234325: Recv: ConfigPushSvc.PushReq[0m
[0m2024-04-27 23:24:57 V/Net 3783234325: Saving bdh session to cache[0m
[0m2024-04-27 23:24:57 V/Net 3783234325: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2024-04-27 23:24:57 V/Net 3783234325: Recv: ConfigPushSvc.PushReq[0m
[0m2024-04-27 23:25:16 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:25:16 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:25:18 V/Net 3783234325: Send: MultiMsg.ApplyDown(MultiMsg.ApplyDown)[0m
[0m2024-04-27 23:25:18 V/Net 3783234325: Recv: MultiMsg.ApplyDown[0m
[0m2024-04-27 23:25:18 V/Net 3783234325: [Http] Downloading forward message from https://ssl.htdata.qq.com:443[0m
[0m2024-04-27 23:25:19 V/Net 3783234325: [Http] Downloading forward message: succeed[0m
[0m2024-04-27 23:25:24 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:25:24 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:27:23 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:27:23 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:27:32 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:27:32 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:27:56 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:27:57 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:29:32 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:29:33 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[96m2024-04-27 23:31:46 D/Net 3783234325: Unknown Transformers528 0x14 template
templId=10126
PermList=[][0m
[96m2024-04-27 23:31:46 D/Net 3783234325: Unknown Transformers528 0x14 template
templId=10305
PermList=[][0m
[0m2024-04-27 23:46:01 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:46:02 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:46:22 V/Net 3783234325: Send: MultiMsg.ApplyDown(MultiMsg.ApplyDown)[0m
[91m2024-04-27 23:46:22 E/Net 3783234325: Exception in decoding packet.
ContextualBugReportException(message=在 MultiMsg.ApplyDown 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose   Decode failure result=192 调试信息: MultiMsgApplyDownRsp#1700751157 {
            bytesDownIpV6=[]
            msgResid=+8/OVwtG2vrMisFQA+ZKptuelp5JaZkzCSb9EBQ1HLOm1wV/OFLTFPJl6Xd/p1vJ
            result=0x000000C0(192)
            uint32DownIp=[]
            uint32DownPort=[]
            uint32DownV6Port=[]
    }, cause=null)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.MultiMsg$ApplyDown.decode(MultiMsg.kt:145)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:585)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:158)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:103)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
[0m
[0m2024-04-27 23:46:41 V/Net 3783234325: Send: MultiMsg.ApplyDown(MultiMsg.ApplyDown)[0m
[0m2024-04-27 23:46:41 V/Net 3783234325: Recv: MultiMsg.ApplyDown[0m
[0m2024-04-27 23:46:41 V/Net 3783234325: [Http] Downloading forward message from https://ssl.htdata.qq.com:443[0m
[0m2024-04-27 23:46:41 V/Net 3783234325: [Http] Downloading forward message: succeed[0m
[0m2024-04-27 23:49:47 V/Net 3783234325: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-04-27 23:49:47 V/Net 3783234325: Recv: MessageSvc.PbSendMsg[0m
[0m2024-04-27 23:56:06 V/Net 3783234325: Send: PttStore.GroupPttDown(PttStore.GroupPttDown)[0m
[0m2024-04-27 23:56:06 V/Net 3783234325: Recv: PttStore.GroupPttDown[0m
[0m2024-04-27 23:56:34 V/Net 3783234325: Send: PttStore.GroupPttDown(PttStore.GroupPttDown)[0m
[0m2024-04-27 23:56:35 V/Net 3783234325: Recv: PttStore.GroupPttDown[0m
[0m2024-04-27 23:56:57 V/Net 3783234325: Send: PttStore.GroupPttDown(PttStore.GroupPttDown)[0m
[0m2024-04-27 23:56:57 V/Net 3783234325: Recv: PttStore.GroupPttDown[0m
[0m2024-04-27 23:56:57 V/Net 3783234325: Send: PttStore.GroupPttDown(PttStore.GroupPttDown)[0m
[0m2024-04-27 23:56:57 V/Net 3783234325: Recv: PttStore.GroupPttDown[0m
[0m2024-04-27 23:58:11 V/Net 3783234325: Send: PttStore.GroupPttDown(PttStore.GroupPttDown)[0m
[0m2024-04-27 23:58:11 V/Net 3783234325: Recv: PttStore.GroupPttDown[0m
[0m2024-04-27 23:58:26 V/Net 3783234325: Send: PttStore.GroupPttDown(PttStore.GroupPttDown)[0m
[0m2024-04-27 23:58:26 V/Net 3783234325: Recv: PttStore.GroupPttDown[0m
[0m2024-04-27 23:58:32 V/Net 3783234325: Send: PttStore.GroupPttDown(PttStore.GroupPttDown)[0m
[0m2024-04-27 23:58:32 V/Net 3783234325: Recv: PttStore.GroupPttDown[0m
